<a href="https://colab.research.google.com/github/SrijaG29/libraries-practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

-> It is a **multidimensional array** library.

-> We can use numpy to store all kinds of data.

In [ ]:
#importing numpy
import numpy as np

In [ ]:
#shapes of an array
# a = np.array([1,2,3])
# a = np.array([[1,2,3],[4,5,6]],dtype='int32')
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[1,2,3]]])
# print(a.shape)

# size of an array
print(a.size)

# items size means the size based on the datatype size like
# int16 = 2 bytes
# int32 = 4 bytes
# int64 = 8 bytes
print(a.itemsize)

# to get total size
print(a.nbytes)

12
8
96


In [ ]:
#array creation using numpy
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# print(a)

# get specific element (r,c) 1D array
# a[1,0]

# get sepecific row
# a[0,:]

# get sepecific column
# a[:,0]

# a[0][1]

# get specific element 2D array
# b[1][0][0]

# np.identity(3)

arr = np.array([[1,2,3,4,5]])
c = np.repeat(arr,3,axis=0)
print(c)


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
# f = np.ones((5,5))
# print(f)

# q = np.zeros((3,3))
# q[1,1] = 9
# print(q)

# f[1:4,1:4] = q

# print(f)

# np.full((2,3),7) (we can generate matrix of 7 with 2r and 3c)
# np.full_like(a,7) (we can generate matrix of 7 with the size of a's matrix)
# np.random.rand(2,2) (we can generate matrix of random numbers with 2r and 2c)
# np.random.random_sample(a.shape) (we can generate matrix of random numbers with 2r and 2c)
# np.identity(3)

array([[0.31902812, 0.20343817, 0.65914742, 0.81643286, 0.98875413,
        0.99598072],
       [0.95170886, 0.53114195, 0.44048222, 0.94792958, 0.83335502,
        0.46074984]])

In [ ]:
# repeating teh values inside an array
a = np.array([1,2,3,4])
f = np.repeat(a,2,axis=0)
print(f)


a = np.array([[1],[2],[3],[4]])
f = np.repeat(a,2,axis=1)
print(f)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [ ]:
a = np.array([1,2,3],dtype = 'int32')
# a + 2
# a - 2
# a * 2
# a / 2
# a ** 2 (root's)
# np.sin(a)
# np.cos(a)

array([0.5, 1. , 1.5])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# a + b
# a - b
# a * b
# a / b


array([ 4, 10, 18])

In [ ]:
# matrix multiplication
a = np.ones((2,3))
b = np.full((3,2),2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
# determinent finding of a matrix which is a single numerical value which is used when
# calculating the inverse or when solving systems of linear equations

c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# concatenate
a = np.array([[1,2,4],[3,4,5]])
b = np.array([[5,6],[7,8]])
# print(np.concatenate((a,b),axis=0))
# np.ndim(a)
# np.shape(a)
# np.size(a)

# reshape  for reshape we need to have the same number of elements in the previous array
# a = np.arange(7)
# print(a)

c = a.reshape(3,2)
c

array([[1, 2],
       [4, 3],
       [4, 5]])

In [ ]:
# converting 1d array to 2d array
a = np.array([1,2,3,4,5,6,7])
# print(a)
# np.shape(a)

# a1 = a[np.newaxis, :]  row_vector
# a1.shape => (1,7)

#a1 = a[:,np.newaxis]  #column_vector
# a1.shape # => (7,1)

(7, 1)

In [ ]:
# indexing and slicing
a = np.array([1,2,3,4,5,6,7])
# a[1] # 2
# a[1:4] # 2,3,4
# a[1:] # 2,3,4,5,6,7
# a[-2:] # 6,7

b = np.nonzero(a < 5)
print(b)

(array([0, 1, 2, 3]),)


In [ ]:
# vstack  it will concatenate 2 array 1 by one like 2 diff rows in one array
a = np.array([1,2,3])
b = np.array([4,5,6])

# print(np.vstack((a,b))) [[1,2,3],[4,5,6]]

# hstack it will concatenate 2 array in 1 one array side by side like in 1 row
# print(np.hstack((a,b))) #[1,2,3,4,5,6]

# rearange

# a = np.arange(1,25).reshape(3,8)
a = np.arange(1,25).reshape(2,12)
# a = np.arange(1,26).reshape(5,5)
# a

# hsplit it can be used to divide array into equal multiple array's
# np.hsplit(a,4)

# unique values
b = np.array([1,2,3,4,1,2,3,4,7])
# np.unique(b)

unique_val , index_val = np.unique(b,return_index = True)
# print(index_val) # here return_index will only return the val of index if the elemnet is unique
#  op 1,2,3,4,7

unique_val , occurance_val = np.unique(b,return_counts=True)
# print(occurance_val) #here return_count will only return the count of the ele repeated
# op 2,2,2,2,1

# for 2d array
c = np.array([[1,4,3,4],[7,6,7,8],[1,4,3,4]])
# np.unique(c)
# np.unique(c,return_index=True)
unique_row, index_val, occurencane_val = np.unique(c,axis=0,return_index=True,return_counts=True)
# print(unique_row)
# print(index_val)
print(occurance_val)

[[1 4 3 4]
 [7 6 7 8]]
[0 1]
[2 2 2 2 1]


In [ ]:
#transpose

# a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# np.transpose(a)

# reverse 1D array

# a = np.array([1,2,3,4,5,6,7])
# b = np.flip(a)
# print(b)

# Reversing a 2D array
a = np.array([[1,2,3],[4,5,6]])
# np.flip(a)

# reverse only the rows
# np.flip(a,axis=0)

# reverse only columns
# np.flip(a,axis=1)

# reverse the contents of the row at index position 1
# np.flip(a[1]) #output array([6, 5, 4])

# reverse the contents of the column at index 1
# np.flip(a[:,1])

# flatten
a.flatten() #array([1, 2, 3, 4, 5, 6])


array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([1,2,3,4,5,6,2,7,7,7])
# np.mean(a)
np.median(a)

4.5

**Numpy problems:**


---


-> calculate summary statistics.

1.   mean, median, mode of totalspend.
2.   mean, median, mode of frequency.
3.   mean, median, mode of avg spend per visit.

     



In [ ]:
np.random.seed(42)
customer_data = np.random.rand(100,3) * [1000,50,200]
customer_ids = np.arange(1,101).reshape(-1,1)
customer_data = np.hstack((customer_ids,customer_data))

customer_data

array([[1.00000000e+00, 3.74540119e+02, 4.75357153e+01, 1.46398788e+02],
       [2.00000000e+00, 5.98658484e+02, 7.80093202e+00, 3.11989041e+01],
       [3.00000000e+00, 5.80836122e+01, 4.33088073e+01, 1.20223002e+02],
       [4.00000000e+00, 7.08072578e+02, 1.02922471e+00, 1.93981970e+02],
       [5.00000000e+00, 8.32442641e+02, 1.06169555e+01, 3.63649934e+01],
       [6.00000000e+00, 1.83404510e+02, 1.52121121e+01, 1.04951286e+02],
       [7.00000000e+00, 4.31945019e+02, 1.45614570e+01, 1.22370579e+02],
       [8.00000000e+00, 1.39493861e+02, 1.46072324e+01, 7.32723687e+01],
       [9.00000000e+00, 4.56069984e+02, 3.92587981e+01, 3.99347564e+01],
       [1.00000000e+01, 5.14234438e+02, 2.96207284e+01, 9.29008254e+00],
       [1.10000000e+01, 6.07544852e+02, 8.52620618e+00, 1.30103186e+01],
       [1.20000000e+01, 9.48885537e+02, 4.82816017e+01, 1.61679470e+02],
       [1.30000000e+01, 3.04613769e+02, 4.88360570e+00, 1.36846605e+02],
       [1.40000000e+01, 4.40152494e+02, 6.10191174e

In [ ]:
totalspend = customer_data[:,1]
# totalspend
print('mean:',np.mean(totalspend))
print('median:',np.median(totalspend))
unique_val , occurance_val = np.unique(totalspend,return_counts=True)
# print(occurance_val)
max_occurance = np.max(occurance_val)
max_occurance_idx = np.where(occurance_val == max_occurance)[0][0]
mode = unique_val[max_occurance_idx]
print('mode: ',mode)

mean: 476.8492328495082
median: 472.7613722472995
mode:  5.522117123602399


In [ ]:
freq_of_purchase = customer_data[:,2]
print('mean: ',np.mean(freq_of_purchase))
print('median: ',np.median(freq_of_purchase))
unique_val , occurance_val = np.unique(freq_of_purchase,return_counts=True)
max_occurance = np.max(occurance_val)
max_occurance_idx = np.where(occurance_val == max_occurance)[0][0]
mode = unique_val[max_occurance_idx]
print('mode: ',mode)

mean:  25.623068502866545
median:  26.02584704495426
mode:  0.25307919231093434


In [ ]:
avg_spend = customer_data[:,3]
print('mean: ',np.mean(avg_spend))
print('median: ',np.median(avg_spend))
unique_val , occurance_val = np.unique(avg_spend,return_counts=True)
max_occurance = np.max(occurance_val)
max_occurance_idx = np.where(occurance_val == max_occurance)[0][0]
mode = unique_val[max_occurance_idx]
print('mode: ',mode)

mean:  99.26063887472752
median:  104.48244528100486
mode:  1.3904261062381407


**Movie Recommendations**


---


-> you have a dataset of user ratings for different movies.


1.   Load and preprocess the data.
2.   Calculate teh average rating for each movie.
3.   Identify teh top N movies by average rating.
4.   Calculate similarity between users based on their ratings.





In [ ]:
np.random.seed(42)
user_ids = np.random.randint(1,21,100)
movie_ids = np.random.randint(1,51,100)
ratings = np.random.randint(1,6,100)
ratings_data = np.column_stack((user_ids,movie_ids,ratings))
ratings_data


array([[ 7, 35,  2],
       [20, 44,  4],
       [15, 40,  3],
       [11, 22,  3],
       [ 8, 27,  1],
       [ 7, 35,  5],
       [19,  1,  4],
       [11, 35,  2],
       [11, 37,  3],
       [ 4, 47,  1],
       [ 8, 14,  1],
       [ 3,  3,  4],
       [ 2,  1,  3],
       [12,  5,  5],
       [ 6, 26,  3],
       [ 2, 14,  4],
       [ 1, 39,  4],
       [12, 27,  3],
       [12,  9,  4],
       [17, 15,  3],
       [10, 15,  2],
       [16, 26,  3],
       [15, 42,  3],
       [15, 13,  4],
       [19, 32,  4],
       [12, 39,  1],
       [20, 49,  1],
       [ 3, 32,  2],
       [ 5,  4,  1],
       [19, 30,  3],
       [ 7, 37,  4],
       [ 9, 23,  1],
       [ 7, 39,  1],
       [18, 45,  2],
       [ 4, 15,  2],
       [14, 43,  3],
       [18, 29,  4],
       [ 9, 36,  2],
       [ 2, 13,  1],
       [20, 32,  4],
       [15,  7,  4],
       [ 7, 22,  1],
       [12, 28,  2],
       [ 8,  2,  1],
       [15, 42,  4],
       [ 3, 45,  5],
       [14,  6,  5],
       [17, 2

In [ ]:
d = {}
for movie_vals in ratings_data:
  if movie_vals[1] not in d:
    d[movie_vals[1]] = movie_vals[2]
  else :
    d[movie_vals[1]] = (d[movie_vals[1]] + movie_vals[2]) / 2
for i in d:
  print(i,' ',d[i])


35   2.75
44   2.1875
40   3
22   2.0
27   2.5
1   3.875
37   3.5625
47   1
14   2.5
3   4.25
5   5
26   3.0
39   2.34375
9   3.0
15   3.125
42   2.25
13   2.75
32   4.3125
49   3.75
4   1
30   3.0
23   3.0
45   3.5
43   3
29   4
36   2
7   4
28   1.1875
2   1.875
6   5.0
20   3
11   4
25   4
33   3.0
41   2.0
8   2
24   2.5
12   4
17   2
19   3


In [ ]:
# np.argsort(d,axis=-1,kind=None,order=None)
movie_id = list(d.keys())
# print(movie_id)
ratings = list(d.values())
# print(ratings)
sort_idx = np.argsort(ratings)
# print(sort_idx)
idx = -1
for i in range(5):
  print('movie_id:',movie_id[sort_idx[idx]],',','movie_raring:',ratings[sort_idx[idx]])
  sort_idx-=1




movie_id: 6 , movie_raring: 5.0
movie_id: 2 , movie_raring: 1.875
movie_id: 28 , movie_raring: 1.1875
movie_id: 7 , movie_raring: 4
movie_id: 36 , movie_raring: 2
