<a href="https://colab.research.google.com/github/SrijaG29/libraries-practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing numpy
import numpy as np

In [ ]:
#array creation using numpy
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# print(a)

# get specific element (r,c) 1D array
# a[1,0]

# get sepecific row
# a[0,:]

# get sepecific column
# a[:,0]

# a[0][1]

# get specific element 2D array
# b[1][0][0]

# np.identity(3)

arr = np.array([[1,2,3,4,5]])
c = np.repeat(arr,3,axis=0)
print(c)


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
# f = np.ones((5,5))
# print(f)

# q = np.zeros((3,3))
# q[1,1] = 9
# print(q)

# f[1:4,1:4] = q

# print(f)

# np.full((2,3),7) (we can generate matrix of 7 with 2r and 3c)
# np.full_like(a,7) (we can generate matrix of 7 with the size of a's matrix)
# np.random.rand(2,2) (we can generate matrix of random numbers with 2r and 2c)
# np.random.random_sample(a.shape) (we can generate matrix of random numbers with 2r and 2c)
# np.identity(3)

array([[0.31902812, 0.20343817, 0.65914742, 0.81643286, 0.98875413,
        0.99598072],
       [0.95170886, 0.53114195, 0.44048222, 0.94792958, 0.83335502,
        0.46074984]])

In [15]:
# repeating teh values inside an array
a = np.array([1,2,3,4])
f = np.repeat(a,2,axis=0)
print(f)


a = np.array([[1],[2],[3],[4]])
f = np.repeat(a,2,axis=1)
print(f)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [ ]:
a = np.array([1,2,3],dtype = 'int32')
# a + 2
# a - 2
# a * 2
# a / 2
# a ** 2 (root's)
# np.sin(a)
# np.cos(a)

array([0.5, 1. , 1.5])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# a + b
# a - b
# a * b
# a / b


array([ 4, 10, 18])

In [ ]:
# matrix multiplication
a = np.ones((2,3))
b = np.full((3,2),2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
# determinent finding of a matrix which is a single numerical value which is used when
# calculating the inverse or when solving systems of linear equations

c = np.identity(3)
np.linalg.det(c)

1.0