<a href="https://colab.research.google.com/github/SrijaG29/libraries-practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#importing numpy
import numpy as np

In [18]:
#array creation using numpy
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# print(a)

# get specific element (r,c) 1D array
# a[1,0]

# get sepecific row
# a[0,:]

# get sepecific column
# a[:,0]

# a[0][1]

# get specific element 2D array
# b[1][0][0]

# np.identity(3)

arr = np.array([[1,2,3,4,5]])
c = np.repeat(arr,3,axis=0)
print(c)


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [26]:
f = np.ones((5,5))
# print(f)

q = np.zeros((3,3))
q[1,1] = 9
# print(q)

f[1:4,1:4] = q

print(f)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
a = np.array([1,2,3],dtype = 'int32')
a / 2

array([0.5, 1. , 1.5])