<a href="https://colab.research.google.com/github/SrijaG29/libraries-practice/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing numpy
import numpy as np

In [ ]:
#shapes of an array
# a = np.array([1,2,3])
# a = np.array([[1,2,3],[4,5,6]],dtype='int32')
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[1,2,3]]])
# print(a.shape)

# size of an array
print(a.size)

# items size means the size based on the datatype size like
# int16 = 2 bytes
# int32 = 4 bytes
# int64 = 8 bytes
print(a.itemsize)

# to get total size
print(a.nbytes)

12
8
96


In [ ]:
#array creation using numpy
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# print(a)

# get specific element (r,c) 1D array
# a[1,0]

# get sepecific row
# a[0,:]

# get sepecific column
# a[:,0]

# a[0][1]

# get specific element 2D array
# b[1][0][0]

# np.identity(3)

arr = np.array([[1,2,3,4,5]])
c = np.repeat(arr,3,axis=0)
print(c)


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
# f = np.ones((5,5))
# print(f)

# q = np.zeros((3,3))
# q[1,1] = 9
# print(q)

# f[1:4,1:4] = q

# print(f)

# np.full((2,3),7) (we can generate matrix of 7 with 2r and 3c)
# np.full_like(a,7) (we can generate matrix of 7 with the size of a's matrix)
# np.random.rand(2,2) (we can generate matrix of random numbers with 2r and 2c)
# np.random.random_sample(a.shape) (we can generate matrix of random numbers with 2r and 2c)
# np.identity(3)

array([[0.31902812, 0.20343817, 0.65914742, 0.81643286, 0.98875413,
        0.99598072],
       [0.95170886, 0.53114195, 0.44048222, 0.94792958, 0.83335502,
        0.46074984]])

In [ ]:
# repeating teh values inside an array
a = np.array([1,2,3,4])
f = np.repeat(a,2,axis=0)
print(f)


a = np.array([[1],[2],[3],[4]])
f = np.repeat(a,2,axis=1)
print(f)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [ ]:
a = np.array([1,2,3],dtype = 'int32')
# a + 2
# a - 2
# a * 2
# a / 2
# a ** 2 (root's)
# np.sin(a)
# np.cos(a)

array([0.5, 1. , 1.5])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# a + b
# a - b
# a * b
# a / b


array([ 4, 10, 18])

In [ ]:
# matrix multiplication
a = np.ones((2,3))
b = np.full((3,2),2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
# determinent finding of a matrix which is a single numerical value which is used when
# calculating the inverse or when solving systems of linear equations

c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# concatenate
a = np.array([[1,2,4],[3,4,5]])
b = np.array([[5,6],[7,8]])
# print(np.concatenate((a,b),axis=0))
# np.ndim(a)
# np.shape(a)
# np.size(a)

# reshape  for reshape we need to have the same number of elements in the previous array
# a = np.arange(7)
# print(a)

c = a.reshape(3,2)
c

array([[1, 2],
       [4, 3],
       [4, 5]])

In [ ]:
# converting 1d array to 2d array
a = np.array([1,2,3,4,5,6,7])
# print(a)
# np.shape(a)

# a1 = a[np.newaxis, :]  row_vector
# a1.shape => (1,7)

#a1 = a[:,np.newaxis]  #column_vector
# a1.shape # => (7,1)

(7, 1)

In [ ]:
# indexing and slicing
a = np.array([1,2,3,4,5,6,7])
# a[1] # 2
# a[1:4] # 2,3,4
# a[1:] # 2,3,4,5,6,7
# a[-2:] # 6,7

b = np.nonzero(a < 5)
print(b)

(array([0, 1, 2, 3]),)


In [ ]:
# vstack  it will concatenate 2 array 1 by one like 2 diff rows in one array
a = np.array([1,2,3])
b = np.array([4,5,6])

# print(np.vstack((a,b))) [[1,2,3],[4,5,6]]

# hstack it will concatenate 2 array in 1 one array side by side like in 1 row
# print(np.hstack((a,b))) #[1,2,3,4,5,6]

# rearange

# a = np.arange(1,25).reshape(3,8)
a = np.arange(1,25).reshape(2,12)
# a = np.arange(1,26).reshape(5,5)
# a

# hsplit it can be used to divide array into equal multiple array's
# np.hsplit(a,4)

# unique values
b = np.array([1,2,3,4,1,2,3,4,7])
# np.unique(b)

unique_val , index_val = np.unique(b,return_index = True)
# print(index_val) # here return_index will only return the val of index if the elemnet is unique
#  op 1,2,3,4,7

unique_val , occurance_val = np.unique(b,return_counts=True)
# print(occurance_val) #here return_count will only return the count of the ele repeated
# op 2,2,2,2,1

# for 2d array
c = np.array([[1,2,3,4],[5,6,7,8]])
np.unique(c,return_index=True)

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([0, 1, 2, 3, 4, 5, 6, 7]))